"""Send period reports by email over SMTP (e.g. Gmail with an App Password)."""

import datetime as dt
import html
import logging
import smtplib
from email.message import EmailMessage

from app.config import settings
from app.models import Report

logger = logging.getLogger(__name__)


def is_configured() -> bool:
    return settings.email_configured


def _fmt_date(d: dt.date) -> str:
    return d.strftime("%b %-d") if hasattr(d, "strftime") else str(d)


def _money(n) -> str:
    try:
        return "${:,.0f}".format(float(n))
    except (TypeError, ValueError):
        return str(n)


def render(report: Report) -> tuple[str, str, str]:
    """Return (subject, html, text) for a report."""
    c = report.content or {}
    try:
        p0 = dt.date.fromisoformat(str(report.period_start))
        p1 = dt.date.fromisoformat(str(report.period_end))
        period = f"{p0.strftime('%b %d')} – {p1.strftime('%b %d, %Y')}"
    except Exception:  # noqa: BLE001
        period = f"{report.period_start} – {report.period_end}"

    subject = f"Your finance report · {period}"

    def esc(x) -> str:
        return html.escape(str(x or ""))

    # --- HTML ---
    sections = []
    if c.get("comparison", {}).get("direction"):
        d = c["comparison"]["direction"]
        color = {"improved": "#2e9e6b", "worse": "#d1544a"}.get(d, "#6b7280")
        sections.append(
            f'<span style="display:inline-block;font:600 11px/1 -apple-system,Segoe UI,sans-serif;'
            f'text-transform:uppercase;letter-spacing:.08em;color:{color};'
            f'background:{color}18;padding:5px 9px;border-radius:4px;">{esc(d)}</span>'
        )
    sections.append(
        f'<h1 style="margin:14px 0 0;font:600 21px/1.3 -apple-system,Segoe UI,sans-serif;color:#111827;">{esc(c.get("headline"))}</h1>'
    )
    if c.get("comparison", {}).get("note"):
        sections.append(_para(c["comparison"]["note"]))

    if c.get("spending"):
        sections.append(_h2("Spending") + _para(c["spending"]))

    cutbacks = c.get("cutbacks") or []
    if cutbacks:
        rows = ""
        for cb in cutbacks:
            impact = _money(cb.get("monthly_impact")) if cb.get("monthly_impact") else ""
            rows += (
                '<tr><td style="padding:10px 0;border-bottom:1px solid #eef0f3;">'
                f'<div style="font:600 14px -apple-system,Segoe UI,sans-serif;color:#111827;">{esc(cb.get("target"))}'
                + (f' <span style="color:#2e9e6b;font-weight:600;">· ~{impact}/mo</span>' if impact else "")
                + f'</div><div style="font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#6b7280;margin-top:2px;">{esc(cb.get("suggestion"))}</div>'
                "</td></tr>"
            )
        sections.append(_h2("Where to cut back") + f'<table style="width:100%;border-collapse:collapse;">{rows}</table>')

    if c.get("wins"):
        items = "".join(
            f'<li style="margin:4px 0;font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#111827;">{esc(w)}</li>'
            for w in c["wins"]
        )
        sections.append(_h2("Wins") + f'<ul style="margin:6px 0;padding-left:18px;">{items}</ul>')

    if c.get("portfolio"):
        sections.append(_h2("Portfolio") + _para(c["portfolio"]))

    if c.get("actions"):
        items = "".join(
            f'<li style="margin:5px 0;font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#111827;">{esc(a)}</li>'
            for a in c["actions"]
        )
        sections.append(_h2("Do this next") + f'<ol style="margin:6px 0;padding-left:18px;">{items}</ol>')

    body = "".join(sections)
    html_doc = (
        '<div style="background:#f6f7f9;padding:24px 0;">'
        '<div style="max-width:600px;margin:0 auto;background:#fff;border:1px solid #e8eaee;'
        'border-radius:10px;padding:28px 30px;">'
        f'<div style="font:600 11px/1 -apple-system,Segoe UI,sans-serif;text-transform:uppercase;'
        f'letter-spacing:.1em;color:#9aa3b2;">Finance report · {esc(period)}</div>'
        f"{body}"
        '<div style="margin-top:24px;border-top:1px solid #eef0f3;padding-top:12px;'
        'font:12px -apple-system,Segoe UI,sans-serif;color:#9aa3b2;">Generated by your finance dashboard.</div>'
        "</div></div>"
    )

    # --- Plain text ---
    lines = [f"Finance report · {period}", "", str(c.get("headline", "")), ""]
    if c.get("comparison", {}).get("note"):
        lines += [c["comparison"]["note"], ""]
    if c.get("spending"):
        lines += ["SPENDING", c["spending"], ""]
    if cutbacks:
        lines.append("WHERE TO CUT BACK")
        for cb in cutbacks:
            imp = f" (~{_money(cb.get('monthly_impact'))}/mo)" if cb.get("monthly_impact") else ""
            lines.append(f"- {cb.get('target')}{imp}: {cb.get('suggestion')}")
        lines.append("")
    if c.get("wins"):
        lines += ["WINS"] + [f"- {w}" for w in c["wins"]] + [""]
    if c.get("portfolio"):
        lines += ["PORTFOLIO", c["portfolio"], ""]
    if c.get("actions"):
        lines += ["DO THIS NEXT"] + [f"{i+1}. {a}" for i, a in enumerate(c["actions"])]
    text = "\n".join(lines)

    return subject, html_doc, text


def _h2(title: str) -> str:
    return (
        f'<h2 style="margin:22px 0 0;font:600 13px/1 -apple-system,Segoe UI,sans-serif;'
        f'text-transform:uppercase;letter-spacing:.06em;color:#6b7280;">{html.escape(title)}</h2>'
    )


def _para(txt) -> str:
    return f'<p style="margin:8px 0 0;font:14px/1.6 -apple-system,Segoe UI,sans-serif;color:#374151;">{html.escape(str(txt))}</p>'


def send_report(report: Report) -> None:
    if not is_configured():
        raise RuntimeError("Email is not configured (set SMTP_* and REPORT_EMAIL_TO).")
    subject, html_body, text_body = render(report)

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = settings.smtp_from or settings.smtp_user
    msg["To"] = settings.report_email_to
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=30) as server:
        server.starttls()
        server.login(settings.smtp_user, settings.smtp_password)
        server.send_message(msg)
    logger.info("Emailed report %s to %s", report.id, settings.report_email_to)
