"""holding price/target_pct, account contribution

Revision ID: 366d8488803c
Revises: 9e7776cfce29
Create Date: 2026-08-27 22:35:52.858220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '366d8488803c'
down_revision: Union[str, Sequence[str], None] = '9e7776cfce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_per_period', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_column('target_pct')
        batch_op.drop_column('price')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('contribution_per_period')

    # ### end Alembic commands ###
