"""initial schema

Revision ID: 5012d485e3de
Revises: 
Create Date: 2026-08-25 23:24:13.594320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5012d485e3de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoryrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('contains', 'exact', 'regex', name='matchtype'), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributiongoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'brokerage', 'roth', '_401k', 'credit', 'other', name='accounttype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('contributed_ytd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributiongoal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributiongoal_year'), ['year'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transactions_cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_plaid_item_id'), ['plaid_item_id'], unique=True)

    op.create_table('paycheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('federal_tax', sa.Float(), nullable=False),
    sa.Column('state_tax', sa.Float(), nullable=False),
    sa.Column('social_security', sa.Float(), nullable=False),
    sa.Column('medicare', sa.Float(), nullable=False),
    sa.Column('insurance', sa.Float(), nullable=False),
    sa.Column('retirement_401k', sa.Float(), nullable=False),
    sa.Column('other_deductions', sa.JSON(), nullable=True),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('employer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paycheck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paycheck_pay_date'), ['pay_date'], unique=False)

    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('plaid_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('checking', 'savings', 'brokerage', 'roth', '_401k', 'credit', 'other', name='accounttype'), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_plaid_account_id'), ['plaid_account_id'], unique=True)

    op.create_table('balancesnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('contributions_ytd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balancesnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balancesnapshot_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balancesnapshot_date'), ['date'], unique=False)

    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_account_id'), ['account_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_source', sa.Enum('plaid', 'rule', 'ai', 'manual', 'uncategorized', name='categorysource'), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_plaid_transaction_id'), ['plaid_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_plaid_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_account_id'))

    op.drop_table('holding')
    with op.batch_alter_table('balancesnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balancesnapshot_date'))
        batch_op.drop_index(batch_op.f('ix_balancesnapshot_account_id'))

    op.drop_table('balancesnapshot')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_plaid_account_id'))
        batch_op.drop_index(batch_op.f('ix_account_item_id'))

    op.drop_table('account')
    op.drop_table('setting')
    with op.batch_alter_table('paycheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paycheck_pay_date'))

    op.drop_table('paycheck')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_plaid_item_id'))

    op.drop_table('item')
    with op.batch_alter_table('contributiongoal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributiongoal_year'))

    op.drop_table('contributiongoal')
    op.drop_table('categoryrule')
    # ### end Alembic commands ###
