"""add item.provider

Revision ID: 9e7776cfce29
Revises: 5012d485e3de
Create Date: 2026-08-26 00:11:37.095785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e7776cfce29'
down_revision: Union[str, Sequence[str], None] = '5012d485e3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='plaid'))
        batch_op.create_index(batch_op.f('ix_item_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_provider'))
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
