// Mirrors backend/app/categories.py CATEGORIES.
export const CATEGORIES = [
  "Groceries",
  "Dining & Takeout",
  "Coffee & Snacks",
  "Transportation",
  "Gas & Fuel",
  "Shopping",
  "Clothing",
  "Entertainment",
  "Subscriptions",
  "Health & Fitness",
  "Housing & Rent",
  "Utilities",
  "Insurance",
  "Travel",
  "Personal Care",
  "Education",
  "Gifts & Donations",
  "Fees & Charges",
  "Taxes",
  "Income",
  "Transfer",
  "Investments",
  "Uncategorized",
];
